version: '3.8'

services:
  service1:
    build: ./service1
    ports:
      - "5000:5000"
    environment:
      - SERVICE2_URL=http://service2:5001
    networks:
      - microservices-network
    restart: unless-stopped

  service2:
    build: ./service2
    ports:
      - "5001:5001"
    environment:
      - SERVICE1_URL=http://service1:5000
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge