name: Python CI Pipeline

on:
  push:
    branches: [ dev ]    # Запускать при пуше в ветку dev
  pull_request:
    branches: [ dev ]    # Запускать при PR в ветку dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd backend
        python -m pytest tests/ -v
